#------------------------------
# Guthub Action: pipe
#
#------------------------------

name: PipeActions

on: 
  push:
    branches: 
      - master
      
jobs: 
  FirstJob:
    runs-on: ubuntu-latest
    steps:
    - name: Print HW
      run: echo "Hello World"
      
    
  SecondJob:
    runs-on: ubuntu-latest
    steps:
    - name: Print HD
      run: echo "Hello Dude!"
      
