#------------------------------
# Guthub Action: pipe
#
#------------------------------

name: PipeActions

on: 
  push:
    branches: 
      - main
      
jobs: 

  FirstJob:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print HW
      run: echo "Hello World"
      
    
  SecondJob:
    runs-on: ubuntu-latest
    needs: [FirstJob]
    
    steps:
    - name: Print HD
      run: echo "Hello Dude!"
      
