#------------------------------
# Guthub Action: pipe
#
#------------------------------

name: PipeActions
env: 
  APPLICATION : "MyFirstPipe"
  PACKAGE     : "project-${{ github.sha }}"

on: 
  push:
    branches: 
      - main
      
jobs: 

  FirstJob:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print HW
      run: echo "Hello World"
    - name: Print ver
      run: |
        echo "msg  : msg1"
        echo "msg  : msg2"
        echo "APP  : ${{ env.APPLICATION }}"
        echo "PACK : ${{ env.PACKAGE }}"
      
    
  SecondJob:
    runs-on: ubuntu-latest
    needs: [FirstJob]
    
    steps:
    - name: Print HD
      run: echo "Hello Dude!"
    - name: Print ver
      run: |
        echo "${{ env.APPLICATION }}:${{ env.PACKAGE }}"
      
