#------------------------------
# Guthub Action: pipe
#
#------------------------------

name: PipeActions
env: 
  APPLICATION : "MyFirstPipe"
  PACKAGE     : "project-${{ github.sha }}"

on: 
  push:
    branches: 
      - main
      
jobs: 

  FirstJob:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print HW
      run: echo "Hello World"
    - name: Print ver
      run: |
        echo "cpu  : $(lscpu)"
        echo "ram  : $(free)"
        echo "APP  : ${{ env.APPLICATION }}"
        echo "PACK : ${{ env.PACKAGE }}"
    - name: List dir
      run: ls -la
    - name: Clone repo
      uses: actions/checkout@v1
    - name: List dir
      run: ls -la
      
    
  SecondJob:
    runs-on: ubuntu-latest
    needs: [FirstJob]
    
    steps:
    - name: Print HD
      run: echo "Hello Dude!"
    - name: Print ver
      run: |
        echo "${{ env.APPLICATION }}:${{ env.PACKAGE }}"
    - name: Check AWS module
      run: aws --version
    - name: Check zip
      run: zip
